### ISSUE TITLE
Calculate temperature from thermistor voltage for telemetry

### ISSUE THREAD

**Issue by nrwahl2** [oresat/oresat-dxwifi-software#1]
From Oliver Jones:
* Calculate thermistor voltage from ADC counts and ADC rail voltage.
* Calculate thermistor R from thermistor voltage (voltage division stuff).
* Calculate temperature as function of R and thermistor T25, R25, and β (or look up T as a function of R in the manufacturer’s published data).

Ryan says the ADC (analog-to-digital converter) value would be read from ADC pin 6 (`/sys/bus/iio/devices/iio:device0/in_voltage6_raw`).

Ryan:
> An ADC is analog to digital converter, it allow you to get analog circuit values with digital logic
> I would probably be best to make it apart of oresat-dxwifi-software, so the value can be sent out over the CAN bus
> ADC pin6  (real name AIN6) is analog pin 6 on Octavo A8, so it is a pin on all BBBs and PBs

**Comment by nrwahl2** [comment]
From Oliver: [manufacturer's data (R vs T for every degree -40 to +150C) for our part, the NTCG163JX103DT1S](https://github.com/oresat/oresat-dxwifi-software/files/12065301/ntcg163jx103dt1s.xlsx)

**Comment by bpranaw** [comment]
Resolve with [this pull request](https://github.com/oresat/oresat-dxwifi-software/pull/2)
